apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-10905
  labels:
    tier: backend
spec:
  type: NodePort
  selector:
    app: nginx-app-10905
    tier: backend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007