apiVersion: v1
kind: Service
metadata:
  name: microbot-nodeport
  labels:
    tier: backend
spec:
  type: NodePort
  selector:
    app: microbot
    tier: microbot-backend
  ports: 
    - name: http
      protocol: TCP
      nodePort: 30013 # The port our networked devices will look on for the application. 
      port: 9090 
      targetPort: 80 # The port of the target ReplicaSet. 
