apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/lkd/ht/portal/code"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
